default: &default
  adapter: postgresql
  pool: 10
  encoding: utf8
  reconnect: false
  host: localhost

development:
  <<: *default
  database: pin3d_development
  username: techstars
  password: techstars

production:
  <<: *default
  database: pin3d_development
  username: techstars
  password: techstars